[build]
  command = "npm run build"
  publish = "out"
  functions = "functions"

# Prevent access to the _private folder
[[headers]]
  for = "/functions/_private/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'none'"
    X-Content-Type-Options = "nosniff"

# Redirect API routes to Netlify functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200 